global:
  scrape_interval: 1s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'triton'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 1s

    # host.docker.interal equiv for linux
    static_configs:
      - targets: ['172.17.0.1:8002']
